from typing import List

from ncl.utils.config.base_config import CommonsBaseConfig, PostgresDatabaseConfig


class BZSDPConfig(CommonsBaseConfig, PostgresDatabaseConfig):
    # SAMPLE_PROJECT_SPECIFIC_CONFIG=VALUE
    #  USER CAN OVERRIDE THIS CONFIG IN .env FILE

    Kave_Negar_API_Key = None
    SMS_VERIFICATION_TEMPLATE = "BazdeVerifyLogin"
    BASE_URL_PATH = "/"
    RIGHT_TO_MINT_COIN = None
    TAX_DEFAULT = 9
    BENEFIT_DEFAULT = [5, 6, 7, 8, 9, 10]
    POST_SERVE_ADDRESS: str = None
    ANALYSIS_SERVE_ADDRESS: str = None
    PUBLISHER_SERVE_ADDRESS: str = None
    LOAN_SERVE_ADDRESS: str = None
    EDUCATION_SERVE_ADDRESS = None
    GHASEDAK_SERVE_ADDRESS = None
    GRPC_SERVE_HOST_AFRA = "192.168.30.125:9999"
    CARTIMEDELTA: int = 6
    PROMETHUES_SERVER_PORT: int = 8220
    REFRESH_INTERVAL_SECOND: int = 60

    GRPC_SERVE_HOST_INS = "192.168.30.125:9999"
    NGL_CACHE_INFO_REFRESH_INTERVAL_SECOND = 20


    HOME_PAGE_CAR_TARGET_URI: str = "DENA_RING_FULADI"

    HOME_PAGE_CAR_PRODUCTION_YEAR: int = 1399

    HOME_PAGE_FUND_CODE: str = "11745"
    HOME_PAGE_CURRENCY_CRYPTOCURRENCY_CODE: List = ["SELL_USD_X_IRR", "BOTH_BTC_X_USD", ]
    HOME_PAGE_INSTRUMENT_ISIN_CODE: List = ["IRO1MSMI0001"]
    HOME_PAGE_LOAN_CODE = "7649"
    # TODO: put the value of the below setting in the runtime config
    CONTENT_HOUSING_HOME_PRICE_ES_INDEX_NAME: str = None
    PRICEABLES_LIST_ES_INDEX_NAME: str = None
    INFLATION_RATE_LIST_ES_INDEX_NAME: str = None
    INFLATION_TRACKER_ES_INDEX_NAME: str = None
    HOME_PAGE_BASE_LOGO_URL: str = "https://api.stage.baazde.ir/images/home_page/"
    INTERACTIVE_NOTIFICATION_PAGE_SIZE: int = 30
    NGL_AMALGAM_CACHE_GRPC_URL = None
    PROMETHEUS_PORT = 8230
    PROMETHEUS_SET_METRICS_INTERVAL_MINUTES = 2
    INFORM_NOTIFICATION_TIME = 1
    DATETIME_FORMAT = '%Y-%m-%dT%H:%M:%S.%f'
    PORSLINE_GET_VOTES_TIME = 5
    PORSLINE_SURVEY_URL = None
    PORSLINE_RESPONSE_ADDRESS = None
    PORSLINE_API_KEY = None
    BASE_PATH_FOR_SHARED_IMAGES: str = None
    BASE_CONTAINER_PATH_FOR_SHARE: str = None
    SHARE_TITLE_FONT: str = 'IRANSans_Medium.ttf'
    SHARE_CONTENT_FONT: str = 'IRANSans.ttf'
    SYMBOL_SEARCH_PAGE_SIZE: int = 15
    MEMBER_LOG_ADDRESS: str = None

    SEARCH_PAGE_NUMBER = 30

