class AssetVO:
    ID = "id"
    NAME = "name"
    CODE = "code"
    PARENT_CODE = "parent_code"
    COMPANY_NAME = "company_name"
    PORTFOLIO_ID = "portfolio_id"
    COUNT = "count"
    BUY_PRICE = "buy_price"
    DAILY_USD_PRICE = "daily_usd_price"
    DATE_TIME = "date_time"
    DESCRIPTION = "description"
    BASE_VALUE = "base_value"
    DATE_FORMAT = " 09:37:52.19547+00"
