version: '3'
services:
  panel-server-django:
    image: repo.narvanventures.lc:9000/bazdeh-server-django-panel:dev-latest
    restart: always
    ports:
      - "8300:8300"
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - RDB_NAME=${RDB_NAME}
      - RDB_HOST=${RDB_HOST}
      - RDB_PORT=${RDB_PORT}
      - RDB_PASSWORD=${RDB_PASSWORD}
      - RDB_USERNAME=${RDB_USERNAME}
      - Kave_Negar_API_Key=${Kave_Negar_API_Key}
      - POST_SERVE_ADDRESS=${POST_SERVE_ADDRESS}
      - PUBLISHER_SERVE_ADDRESS=${PUBLISHER_SERVE_ADDRESS}
      - LOAN_SERVE_ADDRESS=${LOAN_SERVE_ADDRESS}
      - ELASTIC_SEARCH_HOSTS=${ELASTIC_SEARCH_HOSTS}
      - ELASTIC_SEARCH_HTTP_AUTH_USER_NAME=${ELASTIC_SEARCH_HTTP_AUTH_USER_NAME}
      - ELASTIC_SEARCH_HTTP_AUTH_PASSWORD=${ELASTIC_SEARCH_HTTP_AUTH_PASSWORD}
      - CONTENT_HOUSING_HOME_PRICE_ES_INDEX_NAME=${CONTENT_HOUSING_HOME_PRICE_ES_INDEX_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - GHASEDAK_SERVE_ADDRESS=${GHASEDAK_SERVE_ADDRESS}
      - PRICEABLES_LIST_ES_INDEX_NAME=${PRICEABLES_LIST_ES_INDEX_NAME}
      - INFLATION_RATE_LIST_ES_INDEX_NAME=${INFLATION_RATE_LIST_ES_INDEX_NAME}
      - INFLATION_TRACKER_ES_INDEX_NAME=${INFLATION_TRACKER_ES_INDEX_NAME}
      - BASE_PATH_FOR_SHARED_IMAGES=${BASE_PATH_FOR_SHARED_IMAGES}
      - BASE_CONTAINER_PATH_FOR_SHARE=${BASE_CONTAINER_PATH_FOR_SHARE}
      - NGL_AMALGAM_CACHE_GRPC_URL=${NGL_AMALGAM_CACHE_GRPC_URL}
      - RIGHT_TO_MINT_COIN=${RIGHT_TO_MINT_COIN}
      - ANALYSIS_SERVE_ADDRESS=${ANALYSIS_SERVE_ADDRESS}
      - PORSLINE_SURVEY_URL=${PORSLINE_SURVEY_URL}
      - PORSLINE_RESPONSE_ADDRESS=${PORSLINE_RESPONSE_ADDRESS}
      - PORSLINE_API_KEY=${PORSLINE_API_KEY}

    volumes:
      - /home/narvan/baazde-web-panel/images/share/result/:/app/bzsdp/app/logic/interaction/share/temp/images/
      #    command: gunicorn -k gevent -w 9 bzsp.wsgi:application

    command: gunicorn -b "0.0.0.0:8300" -w 4 -t 120 --graceful-timeout 120 --keep-alive 5 bzsdp.project.wsgi:application
    networks:
      - dockernet

    # for debuging
    #command: tail -f /dev/null

  panel-scheduler:
    image: repo.narvanventures.lc:9000/bazdeh-server-django-panel:dev-latest
    restart: always
    ports:
      - "8230:8230"
    environment:
      - APP_SECRET_KEY=${APP_SECRET_KEY}
      - RDB_NAME=${RDB_NAME}
      - RDB_HOST=${RDB_HOST}
      - RDB_PORT=${RDB_PORT}
      - RDB_PASSWORD=${RDB_PASSWORD}
      - RDB_USERNAME=${RDB_USERNAME}
      - Kave_Negar_API_Key=${Kave_Negar_API_Key}
      - POST_SERVE_ADDRESS=${POST_SERVE_ADDRESS}
      - PUBLISHER_SERVE_ADDRESS=${PUBLISHER_SERVE_ADDRESS}
      - LOAN_SERVE_ADDRESS=${LOAN_SERVE_ADDRESS}
      - ELASTIC_SEARCH_HOSTS=${ELASTIC_SEARCH_HOSTS}
      - ELASTIC_SEARCH_HTTP_AUTH_USER_NAME=${ELASTIC_SEARCH_HTTP_AUTH_USER_NAME}
      - ELASTIC_SEARCH_HTTP_AUTH_PASSWORD=${ELASTIC_SEARCH_HTTP_AUTH_PASSWORD}
      - CONTENT_HOUSING_HOME_PRICE_ES_INDEX_NAME=${CONTENT_HOUSING_HOME_PRICE_ES_INDEX_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PROMETHEUS_PORT=${PROMETHEUS_PORT}
      - PROMETHEUS_SET_METRICS_INTERVAL_MINUTES=${PROMETHEUS_SET_METRICS_INTERVAL_MINUTES}
      - GHASEDAK_SERVE_ADDRESS=${GHASEDAK_SERVE_ADDRESS}
      - PRICEABLES_LIST_ES_INDEX_NAME=${PRICEABLES_LIST_ES_INDEX_NAME}
      - INFLATION_RATE_LIST_ES_INDEX_NAME=${INFLATION_RATE_LIST_ES_INDEX_NAME}
      - INFLATION_TRACKER_ES_INDEX_NAME=${INFLATION_TRACKER_ES_INDEX_NAME}
      - BASE_PATH_FOR_SHARED_IMAGES=${BASE_PATH_FOR_SHARED_IMAGES}
      - BASE_CONTAINER_PATH_FOR_SHARE=${BASE_CONTAINER_PATH_FOR_SHARE}
      - NGL_AMALGAM_CACHE_GRPC_URL=${NGL_AMALGAM_CACHE_GRPC_URL}
      - RIGHT_TO_MINT_COIN=${RIGHT_TO_MINT_COIN}
      - ANALYSIS_SERVE_ADDRESS=${ANALYSIS_SERVE_ADDRESS}
      - PORSLINE_SURVEY_URL=${PORSLINE_SURVEY_URL}
      - PORSLINE_RESPONSE_ADDRESS=${PORSLINE_RESPONSE_ADDRESS}
      - PORSLINE_API_KEY=${PORSLINE_API_KEY}

    command: python -m bzsdp.manage scheduler
    networks:
      - dockernet

networks:
  dockernet:
    external: true