class InteractiveNotificationVo:
    TYPE = 'type'
    DATA = 'data'
    DATETIME = 'datetime'
    MEMBER = 'member'
    NUMBER_OF_UP_VOTERS = 'number_of_up_voters'
    FIRST_NAME = 'first_name'
    LAST_NAME = 'last_name'
    TAG = 'tag'
    CONTENT = 'content'
    NEWS_OR_ANALYSIS_ID = 'news_or_analysis_id'
    TIMESTAMP = 'timestamp'
    COMMENT = 'comment'
    GAME_ID = 'game_id'
    COMMENT_ID = 'comment_id'
