class HealthCheckVo:
    IS_HEALTHY = 'is_healthy'
    HEALTH = 'health'
    RESPONSE_TIME_MS = 'response_time_ms'
    POSTGRESQL = 'HealthCheckDao'
    ELASTICSEARCH = 'HealthCheckESDao'
    REDIS = 'HealthCheckRDDao'
    GHASEDAK = 'GhasedakAdapter'
    GILLETE = 'CarAdapter'
    POST_SERVE = 'WebPostServeAdapter'
    PUBLISHER_SERVE = 'WebPublisherServeAdaptor'
    MEMBER_LOG = 'MemberLogAdaptor'
